### ISSUE TITLE
matching query does not exist error 

### ISSUE THREAD

**Issue by smyja** [charlesthk/django-simple-mail#10]
i get this error when i run `python manage.py runserver`
```
[C:\Users\USER\Desktop\cvbn\djangovueto\vuewe\aview\core\mails.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\users\user\appdata\local\programs\python\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\simple_mail\apps.py", line 13, in ready
    autodiscover()
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\simple_mail\mailer.py", line 102, in autodiscover
    import_module(module)
  File "c:\users\user\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\USER\Desktop\cvbn\djangovueto\vuewe\aview\core\mails.py", line 12, in <module>
    headers={}, cc=[], reply_to=[], fail_silently=False)
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\simple_mail\mailer.py", line 43, in send
    mail = self.get_mail()
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\simple_mail\mailer.py", line 31, in get_mail
    return SimpleMail.objects.get(key=cls.email_key)
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\USER\Desktop\cvbn\djangovueto\sert\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
simple_mail.models.SimpleMail.DoesNotExist: SimpleMail matching query does not exist.](url)
```

this is my mails.py 
```
from simple_mail.mailer import BaseSimpleMail, simple_mailer
from django.contrib.auth.models import User
from .models import Profile

class WelcomeMail(BaseSimpleMail):
    email_key = 'lcomier',
    to = 'smyja9ja@gmail.com'


welcome_mail = WelcomeMail()
welcome_mail.send(to='smyja9ja@gmail.com', from_email=None, bcc=[], connection=None, attachments=[],
                  headers={}, cc=[], reply_to=[], fail_silently=False)
simple_mailer.register(WelcomeMail)
```

i think i am doing it wrongly.

**Comment by charlesthk** [comment]
@Smyja it seems an email with key `lcomier` is not found in your database, did you registered your email with `python manage.py register_mails` command ?

**Comment by smyja** [comment]
> @Smyja it seems an email with key `lcomier` is not found in your database, did you registered your email with `python manage.py register_mails` command ?

Yes

**Comment by charlesthk** [comment]
@Smyja this block of code :
```
welcome_mail = WelcomeMail()
welcome_mail.send(to='smyja9ja@gmail.com', from_email=None, bcc=[], connection=None, attachments=[],
                  headers={}, cc=[], reply_to=[], fail_silently=False)
simple_mailer.register(WelcomeMail)
```

Should not be in `mails.py` file. You should instead import `WelcomeMail` from another python file (`views.py` for example).
